language: node_js
node_js:
  - '8'
sudo: false
before_deploy:
  - CI=false npm run build
deploy:
  provider: s3
  access_key_id: AKIAIZ6ARLLJM5A23ENQ
  secret_access_key: '$AWS_SECRET_ACCESS_KEY'
  bucket: kylecsutton.com
  on:
    branch: master
  local_dir: build
  skip_cleanup: true
env:
  global:
    - secure: C7Kx8Eemph69QoeAbmOt1ncGz988hRIiUWRsFWck5lSFSyauP7WoB6d8fZTLisRZjzWMdmzSBvQ8iuKWMvCIWl0XbLT2u7pOWFHA6YEWeC/pOyjehcJYY9RjtgsKu0WTpaO6KQo05WZV9/NysbH5qrpgQ+yl0z6Bj2UU2fEHak/ZlNvNHn7RAz9WEWsTKXcDfYdVB5gbnE8CxL1o6DDuZpXfvXjg9Tf4xck2aCHDnrIzJHwUMPislcONzJT9RFepUV7tTKSUZX3eSDt0qIK0W2FdYe70/Axxsq1Zw2s4rk/mU2Xd3WVEvJ+FuNdw9Jins+mxYisfXwSismULSJy72M7ERi/dWYoiC9xusCAAjfoCwPUhxM79sjXlX8OhHcuha3y/71rtJTdSOve/mK7OJnXmPTHk+18wD9dEt6tzZxJ4HUmjepVOPDKKapNcB0Y8Yy3D70MgbQiBs8f7kCcuw3U7CXwZ3kG8CdNyrJbmpZCoQkaVbdBg3jUHOkYGYdoHNqPGy1PrSPFEWND9RretWQdrpAUY4mSUENJ5Ia/qXAhEU8v0zOOpentyGX0KbtmsBj3NpgLWOkOJy2PCjhfKQ/bTeYFfI3OcD0z/I+1NlDaizEF5S3U/xHhRIf1igiPlmI/hbj4GqvDeC3rTK0LfBPIggPIa+HyRZAgsng1ihWw=
