language: node_js
node_js:
- '8'
sudo: false
jobs:
  include:
    before_deploy:
    - CI=false npm run build
deploy:
  provider: s3
  access_key_id: AKIAIZ6ARLLJM5A23ENQ
  secret_access_key: "$AWS_SECRET_ACCESS_KEY"
  bucket: kylecsutton.com
  on:
    branch: master
  local_dir: build
  skip_cleanup: true
env:
  global:
    secure: kDt58cpcoSNoV1OCZpx2bHdtWR0n9euX5NZ/YjSntEVIZ1bUfyCM0Ms4qe+SS6au57ApkpFle21PlE6pqnAwcPGPnZEo+dgWhev0ddWp6LbgpZdRzrZ07efFdYmh0wGqJ2COh7ejewgEslyBAZoVrFUCcZtVbt+jGT/DFTuBht5Fdc0Lmy87xhJl6CY0MmK1mnGT2Z5VeQzoPthqayMtrNLUcoPJYyujXxLwv0O/Hu61YvE+ZLtWMDYel9EKSL4MtehKplY2oXE0EClVsU71B7YocrohD8gT4stzBYt/QdlsdEYCKa8a0Ia6NamqRXyHeSQfnH4OMKth5RLGeKzZPEMYBaVYJ2hivYZXOgkH10x22a5ZcPSVlEyjfixU9EEs1K8xNXtGVCWoCNL6/K/q7g4NYPPAzyUWym2iPvZut1v+XwTk+OTUof4t7uhzEJEmSZJqboNk419N3vSd21QVs3Xhr8e6evrZcYVyHwAbmxU6CMFqwIUkmxGi+BJgxg3m+Z1wWnDOqnfGUiC8Yx7zXVTE4TLcjvAAqT/r3kFpoBP7qIKcvdgdRuqPg3Z5tCpHBXGKLl91cAvxQlTsz9l/IkAhOYmPaNe9QvuQOGI6lbu6oR0AwF/HBpv+784NFPVEwAvVTnvVM7Sm3ltjQD5AEA4hZB0rtUx1nWoWQ3rLt9o=
