language: node_js
node_js:
  - '8'
sudo: false
jobs:
  include:
    before_deploy:
      - CI=false npm run build
deploy:
  provider: s3
  access_key_id: AKIAIZ6ARLLJM5A23ENQ
  secret_access_key:
    secure: i3vJKa498oCB4U5z8WxGEY3edybLC6BiGd+yfOti1FRds8wWGm7Vgq9YBJLxxhlatDlrDkYc+qlSOyUWYFFNtgypbkWFxzzk+y0jaM37SJ5rts9pTkz0JnttBLMsCJyYW9WSnTamXbz4wdlNO7Gvp7kLIuL/9VNF4J1mtKdJFrc9KHsM5egZhD7c8lpw1BSCIxSIMe5TK7Oz+Yhgnwj7b5lzgWZ5IEYO5v9grIoRRauIIlUeGWXuLswR+g1ELpB3BxIRiDLl1wuNLUvzfNS4j1IOXtEHLbZ4HkL9Wp4Iuq9mxa+UVHlO2Mhr/umxhPYIkjhT3drn1i8+B17Oz7aiVne/stoL0Y5OvJiKtxJP0x+Cg1Uiq004F1ZZYXgS8+l6bVvdOdKJB233MTGEap8Ck7crHisrCWbbXXvPEg9Ev9EC5v7nRny1mSodlnG8zUeyFYjJQSSpcsDAwytZbJnnSCQFkMBT13oe6AeIZTY3Vt5DoILBUDRx/8fIe9QDKHLlCf8GZAbpglZR14JQDLkz0J6g1jyVSx2XqYAGFj9slrJ6f2IpdZdTah8yEUF+SLr593DLOAYc66IH/bYrJ+usgmini6U/PdSJgYR5yoNL5/1ksZt7lwf7vmcGJrvZ9p/0so2bajuhXBh2H8hFGcJqOc+k3a6UlR2o+CUtOQGItYw=
  bucket: kylecsutton.com
  on:
    branch: master
  local_dir: build
  skip_cleanup: true
