language: node_js
node_js:
- '8'
sudo: false
jobs:
  include:
    before_deploy:
    - CI=false npm run build
deploy:
  provider: s3
  access_key_id: AKIAIZ6ARLLJM5A23ENQ
  secret_access_key: "$AWS_SECRET_ACCESS_KEY"
  bucket: kylecsutton.com
  on:
    branch: master
  local_dir: build
  skip_cleanup: true
env:
  global:
    secure: J3onVyPpI/1RXrojL6RuV8VZ/UU36cUsKnWoXNh7O/vSWjXusQfw6oQvZ31MXLtQqzHgxTVvl5MZ+pQyk4yHtKpKMyY+W2CND9vgd1wwF0JsoJIE+bCwyVKsRbp6hvdbcOIUXurZqcAZVIhT3pRYkKNKxIue/hjoYIkHFwOR5FB5mMGzXcRJ4WZECTBx71/ANmJRKnV5T8gtof3ST2zGAFClUej7Z8Qg1NdS23Y5LdlV0oIxQO6yWHKCejRfO66s5xDU5aZnIfADUjT93vvAFQfEp3mJKEAkAq8cZdIyWoEqvNZHLin9nMJmo1I/bR3x+OvI+roiVWolCVCxmPyQF3BWq8/yvX9rI4HZhcinnw20pWY9t6pHR9dQd4h+qwlyk1ieydmaKhHd7TCebPCLHQgbTub5OYxcSUb2O3OHOfHMuusH4oonqPf9i9Vi7U1HIf/+dE8vZqON6qYmz/6M+b1uH+MJhFYcxX6itlAUGjDDKokyyfpGR2PDhn6REfGFoY58JaHtmuhu63fYwl+LytrXC6ZY6quDPl50HYnk5bswGXXMMGHpfss9qlO2dXdJU9zV2aitItdtUOmklzsmITA25TaQSVgFR1FmC6aud+t7JOe2K7DoCWJ9PvQmI+GE2Z49PbEv8tkCOyzxKeZDBiWMSkwi7uZ6qvbv/iBsqlQ=
