language: node_js
node_js:
- '8'
sudo: false
jobs:
  include:
    before_deploy:
    - CI=false npm run build
deploy:
  provider: s3
  access_key_id: AKIAIZ6ARLLJM5A23ENQ
  secret_access_key:
    secure: AJNcxmFyOiD5mbh4D7O8o104I/66PQL0LuVCwaMx2u8ETeMu+8XlLxO3xCVGbS4gZaIODJknb5kcJNdJwqVDLoEftsLATQJpsNSxN6Phf4byW9xD8gfkysHvp/KGB5manpqGIAqRlRpxQQruM3npdE76/qbrO3rg1fLWJOsx2reLpSbEFT8G6BDa1WbTmWRl/V1g3jLijt5jNdE2rWOxB12aBGcOeRpCa1wK9kyRlh7J+hibLucS2V/238Uc5qxpT6HwxBtu6UjV/qu4//fYv5uRD9tzPhsJcKm8lC6Koxu7Yz2+CIvUJsbMgWsooWw3czsYh3bmm3qDQs45ESLW2hfbaHasF4w0meZQB8WKcGUQhWH5ap1yI7Ez5BSwmRHeNaH2CwsUCk94jkU5PO2ARW/1X51FBJng07n0jJBf1Om+ipIM6OyuFkleBYoqyrlA3HWlzgretFmXQxpirdKAH2wzzwal1uGujMredal0VUOzkzXonHoJcVsUdXvT9cRn3mmTg2jASEV/TTu8wPtIQGrKP50ktxs4lnld79EMQYTv9cMLyR+9AVy8XHrsClUFd9JSg6tyB9Cb25mz+6FNN1GmzLSv5MS1Cf0kvy5J1LnvIQhs9OM/ypP0zr+oNwFgJWArQiR9zOIpYmJZkeNF745RUR4UartM2DhgH3z9NbQ=
  bucket: kylecsutton.com
  on:
    branch: master
  local_dir: build
  skip_cleanup: true
