language: node_js

node_js:
  - '8'

sudo: false

jobs:
  include:
    before_deploy:
      - CI=false npm run build
    deploy:
      - provider: s3
        access_key_id: 'AKIAIZ6ARLLJM5A23ENQ'
        secret_access_key: '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'
        bucket: 'kylecsutton.com'
        on:
          branch: master
        local_dir: build
        skip_cleanup: true
