language: node_js
node_js:
- '8'
sudo: false
jobs:
  include:
    before_deploy:
    - CI=false npm run build
deploy:
  provider: s3
  access_key_id: AKIAIZ6ARLLJM5A23ENQ
  secret_access_key: "$AWS_SECRET_ACCESS_KEY"
  bucket: kylecsutton.com
  on:
    branch: master
  local_dir: build
  skip_cleanup: true
env:
  global:
    secure: Sx1oZFMj59NP5qILQ0RBpuagvxDn/vbGRICHDyglkuP+SjuxVKD1X5TIxtu5ZPxFcwl5XX3i/mNsvkn3v2XFz7vUXBBxVoqUNkIiTZSdJGm4DW9cY69ICb8hvOdkjj0k7AygcAdy0+IM4PSb4FMCtYqrnr1RXdwXVV1VUKG3cVv5KobvHEE6Uqhy+aWplTvrtx70hXHwUMk5/T9+kTko544kI7IQ6Rw1lhVvmeuUnQaeWP2CKQZrENQMt5eDX0nFi+aCk/CJrNvepKGYwqZKWd54cKRuG1QrmWoc23h+98jH4/AJ+Iaopk9nOlP3soRV1bfSVBuExsE31A7cYikIRDKbcGQ2b6RctVTh/x0fcAXNzRGIjeMseLjYLZQdzKujQ9Mj1Gqk5dBjN1GaC2LgIFtzdsygdQaN7cA7kSdSfdV0VprYCn7+/G/MC/+cMef0tjOsGCGdGOKAt3FmVwpU2BDweuPI3KPOU/CDXmQiXPr2uOnjTM+yh99EyTRjt83gKW9BQFpkH1gBmeq8NOXSGzJpA0GUO40/w6sN1bDMttgEUTTg1o+flfALF5Tiqi4FWkLgy5fhZWgeMjyOyc6XZbekaSE6EcDTcjccYt6eFU771wRet9Pe/CcbhSKFNKJvB7epkdu00FQq34goQr65vxcLYPoec9sdns9LwG2aMD0=
