language: node_js
node_js:
- '8'
sudo: false
jobs:
  include:
    before_deploy:
    - CI=false npm run build
deploy:
  provider: s3
  access_key_id: AKIAIZ6ARLLJM5A23ENQ
  secret_access_key: "$SECRET_ACCESS_KEY"
  bucket: kylecsutton.com
  on:
    branch: master
  local_dir: build
  skip_cleanup: true
env:
  global:
    secure: j9PKpppNMdhha76FzK9AY54+bApbDWX7HbIkgqDTqxboxAT4wT2ZncelmPQxuNGYPRbwwMmJb3RnDqqLoviR16Dduz+684oWEUr0Nb1B4V1l7Bt13pSIpc+Uh/18vlNLevkSE2YRs6xhChDc3Kc/vcoYHJ+aPV/yZ3I9Jzw+M+ifsiMfWt7xmfFgIY3f3cCmqu4Msh3BkKn1DEmx40gMhPcyZIy5x+sR+nj5aNwgL1PmnC/4IyoLAy1jQtGK3ohLbsilbCm/b5CsfxSQfaAXEl9dJ1wXiHxLRPcDo58CmsOz+den8w9PYYhVMIib5Eo75UBDNtDnHygxzNou5BM6NfmG66+ykBGBiYDWXh7iQkJ3G9qdp69J6qOcg0A9kx9q1lHybdNh6dYC/AMUdv28VG521VTf1w0glgVsd5JvhEBLURHtIwaVQeDj2J8P/VJM6SlaC6ORYK89PY9i1LxN925Yx6hth3C4lnwetBVl1diiIOB2SdpISAV1x7qOfGQyWHfct530tNCvtNQJLRNyP1AClM5kuIAm+8KK4OU+LGFCXTMO6UQqtCp1hF4AL5Km0niQi9qmHK1OE4a+ENlPMskObmS67sO8Wey3lOaVYWxGoDCe/SwMoaqcN6/k1crk+pJKZQXZFpC2eifmx4W0qrW6gwgIuchcjxozzLyHbpw=
