language: node_js
node_js:
  - '8'
sudo: false
jobs:
  include:
    before_deploy:
      - CI=false npm run build
    deploy:
      - provider: s3
        access_key_id: AKIAIZ6ARLLJM5A23ENQ
        secret_access_key:
          secure: SRBdjUDRoP3xp2vy183833XTGY/YS6wc3TS/YG+QZlDkVRVeP+A4+WA9B6iMNmZ3ussTH4VLyE1ukXl0JHTuX2Pic/9ypgzdWL+VQqKVvSyEkwxBX+Pn2qTGbqYbj1Rpbrbar0WpsIkVNy+uPXcmVnZJiVaRA7kSgbWGX15TuT1CiiQPOnXhjzSpauj12bTEuT05ZoWaR8k2X1mrwm02tWR9l33R+IbWL+Op0/v8HVDc8IzIB3AD4f3+ly4jvK9s2CDPsO6OxtRoJWjtDqceMIfD06Lxn7+2Q6pIlFv+EHFb99wpzwvyakJHkrEuy7/5Y5mRPyqnrypvgfw338iwpZSXfQjdxJSQkL1+QiL2O0qSFvUN5ydmIH7A1R2Ac0iT1t/MScNVLqChFFEojp0uF1SzhK6kreTmN4QzAXaFD7wQFA6AMXmj4pehBAb0rXacWISL1mVYsDUrgcx39T+Q+oTNPS18RVnxwfKJxD9m50ocZdLdBznbJ6GCZgtdi6Ajzzv6e2DW0Q2LkC6/S4NwFTfHMRzl5kIAZ0VKBWrhv2OLAkkjHx72fV1twtzEG/oyI4z8agQLWJ60YsGWdVIGjs4vGNdxUsmki31a6LzEQkCuou/6drupnyFcI/xv1QKd8nD5luPh3sWY02ON8B5M++Al0irLWRG9CMa1Scp7Hj0=
        bucket: kylecsutton.com
        on:
          branch: master
        local_dir: build
        skip_cleanup: true
