language: node_js
node_js:
  - '8'
sudo: false
jobs:
  include:
    before_deploy:
      - CI=false npm run build
deploy:
  provider: s3
  access_key_id: AKIAIZ6ARLLJM5A23ENQ
  secret_access_key: $SECRET_ACCESS_KEY
  bucket: kylecsutton.com
  on:
    branch: master
  local_dir: build
  skip_cleanup: true
env:
  global:
    secure: NX2eBHoBuD52E3N4ErnHzF07N4Z/OhUxg7wvcvJp7gNu19U43k/dlzbsNqM4VOrxJtIh4Aw3vxpfpVkqUTlGpb2M3E/P746qanP5nihsCrmwQIg7a/a8VNu1kENnDkhIuqA0Uxq4KGODwfM5QS9VpyxANNZolu/GcmywS5uAz3aQuqWVcV3FXWFf/4v4j53YHKfAEWXeqq2nWWr7ioFqo/0+aqx+Biesm+/MXCD+5bp1q0nKexSXS1HuDluYp7ykDTWjHbDTSVvqmAvAtDqpkpvcEinOzgBRNnwCiBJpp9zykpEffuHWsMSr+rzmxcZN+lEgC3jYFuPzMF0VEB87sfEiFGDtcDGQcCwu6STT47yU5b+MvoxOd9JtAhmYBEME2zem2qZ8lJ1no0hcTEeRgVDXEcRZ7gWu8qMMmspgY8H3JPIkDe5+6RkXoU+Y9xdQOgJFmZG5P8++6yb7G+iF9oDE1Q2h7Ho6oDhoaY4X0WfYpDDBW806wUjW0GcgXiINCRDJ/TuOfRj4JQhrqmSKRLygv7MtBFhU64C1GAn7uZ0KUgSSbMRbNbSHP+z9Hke996Z8bVxZKuNbWgpDBodK6sVUGFMeAFfnHTaxmyDQytJY+67TWnQ41g2sLlL1EWVe1cRyx/S230XZ9xnyusHUY/QpA+f+uPEwYk5xAakEBWY=
