language: node_js
node_js:
- '8'
sudo: false
jobs:
  include:
    before_deploy:
    - CI=false npm run build
deploy:
  provider: s3
  access_key_id: AKIAIZ6ARLLJM5A23ENQ
  bucket: kylecsutton.com
  on:
    branch: master
  local_dir: build
  skip_cleanup: true
env:
  global:
    secure: ZX9QjF/LuXuXEgdhPlL2j8CJ/J9x6473XO3ZN3dZJLrOoLrJlVifZ4J0HksfzMbiXWPmnuCw7yXnS/8bFH1AE1FWLOyGunqWjSC+6ZDYS1zjhSri1ZM2h4qTSiHnza1YGWh7T82MHA4iwBfiXb78kIm/6eUsHcyBdI3dG5gBCoDbhwGQNZJH5vL/SGeRDEvTQpaEurKtP/NIKFAJ6CZvLFaDBAjyv6B8/HNzE2t/TTH3AXDckXXr/5w66Luv9cVEfvdUD6bm54mSv44gVIRVxhQ328KvmUeX5L3gOwsIoD0dga48RV5k1VhMxjTWGSETS3x8kguqpiCQCdQqtkvKL7jdTehd2AK8Yl4liZVZiPjlcf7Qt95V/haJN0PHOItE3sPN872nQWmJxRYD/pJCVo9BNQvn6ZcxPDf/QAkKuXU/QEY1RdfOwRe+4C5Vg75LwHiTNRugWMbWavJXaf1GCBIfS1S9ffysSmxnz29X8B26+uhn1OSzKRu5ZwzVtfbCXzq/PPlmd2EnY718wsRo8r2e/6tQbPgPHr5E0R7wXkeCbaHWyFWobdcTvSGiXW2KbfCayVbTxh3P91sPCtsyTvv5Da0VYaeeHhOlyFoyC0wsZZJH0hddiFSgDSU7LCTSZn3HhuzMTI7jy8r/tA9+66XfNo4rR3xEwArsB5a08XI=
