language: node_js
node_js:
  - '8'
sudo: false
before_deploy:
  - CI=false npm run build
deploy:
  provider: s3
  access_key_id: AKIAIZ6ARLLJM5A23ENQ
  secret_access_key:
    secure: 'j0tGzQaXsy3B2aoj5T4AsbbACOVuTHtA+uy4sU0rEJ7hrvr4T6ksaFD/Oa8qzm4e9OjX4UuXUzoSqchgzMR5NKpiHWm6PG6dovByv43zW28UVXV3H/4jN+YogJ7OK0vAVtmbCCXq98s18nxIP5F48wpbmZnO4u1kf8Z7JPrgzsUVdnCirpK4NZnltxoCTw2eo9MVlrvlTYBokrDWy8EBotdALXSFcose6tT1lauTN+I4nuHVmMdGxiVfUZ9+Giixbk5e3usE3foRy6oxpn2LjZEAgM/o1vtXye3KSxKZ/851hfKIR/bo0fqHyGB/pL2FArBnniI8XmiOvxZ8VqNI/amluSAgJep7WkBTK4rJQpb8BL2GDCBsKaU2LTev4nY6PeYxNpjgsN9HkB+uXOgmg5VprkqxzfQqWhKB5fYqHb7B+87Dm/FvGCCbC5XSYpAPTSrSgqy+vu2Zao2aJMJJk98EL5xQm44+ZDJylSNSetVEjCxYvuKAkSn64HyM3pFOP7IFiOKE2huPx9oOmCMXKy5jDVjvT8dEgOnOwJpuF7vLhKOt5Gxrhp8mCQ1SMJpZt39QfUqP8wrrhto/SXx69MFg5m09o3DjyaxOZApxaFBzA/9hBVnUm81sFFBAjpV8kUdC4xZm4qwzDe8wxikhU5176wnEcmmjdq8nH8eqh74='
  bucket: kylecsutton.com
  on:
    branch: master
  local_dir: build
  skip_cleanup: true
